server:
    port: 23001

spring:
    config:
        activate:
            on-profile: prod

logging:
    level:
        com:
            zaxxer:
                hikari: info
                hikari.HikariConfig: info
        jdbc: 'off'
        jdbc.audit: 'off'
        jdbc.connection: info
        jdbc.sqltiming: debug
        root: info